### ISSUE TITLE
Sharps and flats that change notes (e.g. C-flat) don't work.

### ISSUE THREAD

**Issue by nateGeorge** [mdoege/PySynth#7]
Trying to use notes like C-flat or E-sharp give an error, e.g. `KeyError: 'cb'` for ('cb', 4) as a note.

Code to reproduce the problem:

```python
import pysynth as ps

test = (('cb', 4), ('e#', 4), ('b#', 4),
        ('fb', 4))

ps.make_wav(test, fn = "test.wav")
```

output:

```python
Writing to file test.wav
[1/4]	
Traceback (most recent call last):
  File "PySynth/pysynth.py", line 212, in make_wav
    a=pitchhz[note]
KeyError: 'cb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PySynth/pysynth.py", line 214, in make_wav
    a=pitchhz[note + '4']	# default to fourth octave
KeyError: 'cb4'
```

expected output:
```python
Writing to file test.wav
[1/4]	
```

Tested in both Python2.7.11+ and Python3.5.1 on ubuntu 16.04LTS.

**Comment by mdoege** [comment]
Should now be fixed by https://github.com/mdoege/PySynth/commit/910ee2165c42ddab31af13874937972aeee0def7
